[2022-06-14 08:33:48,305] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: table_postgres.create_postgres_table manual__2022-06-14T08:26:01.058013+00:00 [queued]>
[2022-06-14 08:33:48,341] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: table_postgres.create_postgres_table manual__2022-06-14T08:26:01.058013+00:00 [queued]>
[2022-06-14 08:33:48,344] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 08:33:48,346] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2022-06-14 08:33:48,347] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 08:33:48,386] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-06-14 08:26:01.058013+00:00
[2022-06-14 08:33:48,402] {standard_task_runner.py:52} INFO - Started process 3134 to run task
[2022-06-14 08:33:48,424] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'table_postgres', 'create_postgres_table', 'manual__2022-06-14T08:26:01.058013+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/create_user.py', '--cfg-path', '/tmp/tmpt28gf7cg', '--error-file', '/tmp/tmpe80i23su']
[2022-06-14 08:33:48,430] {standard_task_runner.py:80} INFO - Job 62: Subtask create_postgres_table
[2022-06-14 08:33:48,608] {task_command.py:370} INFO - Running <TaskInstance: table_postgres.create_postgres_table manual__2022-06-14T08:26:01.058013+00:00 [running]> on host 38a912dff3f2
[2022-06-14 08:33:48,883] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=table_postgres
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-06-14T08:26:01.058013+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-14T08:26:01.058013+00:00
[2022-06-14 08:33:48,918] {base.py:68} INFO - Using connection ID 'postgre_sql' for task execution.
[2022-06-14 08:33:48,944] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 186, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.internel" to address: Name or service not known

[2022-06-14 08:33:48,972] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=table_postgres, task_id=create_postgres_table, execution_date=20220614T082601, start_date=20220614T083348, end_date=20220614T083348
[2022-06-14 08:33:49,006] {standard_task_runner.py:97} ERROR - Failed to execute job 62 for task create_postgres_table (could not translate host name "host.docker.internel" to address: Name or service not known
; 3134)
[2022-06-14 08:33:49,055] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-14 08:33:49,189] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
