[2022-06-12 04:18:24,185] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.choose_best_model scheduled__2022-06-11T00:00:00+00:00 [queued]>
[2022-06-12 04:18:24,223] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.choose_best_model scheduled__2022-06-11T00:00:00+00:00 [queued]>
[2022-06-12 04:18:24,224] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 04:18:24,225] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-12 04:18:24,226] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 04:18:24,260] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2022-06-11 00:00:00+00:00
[2022-06-12 04:18:24,279] {standard_task_runner.py:52} INFO - Started process 3270 to run task
[2022-06-12 04:18:24,311] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'choose_best_model', 'scheduled__2022-06-11T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmpf9c10jbh', '--error-file', '/tmp/tmpu8s5x7e_']
[2022-06-12 04:18:24,315] {standard_task_runner.py:80} INFO - Job 10: Subtask choose_best_model
[2022-06-12 04:18:25,142] {task_command.py:370} INFO - Running <TaskInstance: my_dag.choose_best_model scheduled__2022-06-11T00:00:00+00:00 [running]> on host f95f507e9417
[2022-06-12 04:18:25,568] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=choose_best_model
AIRFLOW_CTX_EXECUTION_DATE=2022-06-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-11T00:00:00+00:00
[2022-06-12 04:18:25,583] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_dags.py", line 11, in _choose_best_model
    accuracies = ti.xcom_pull(task_ids=[
NameError: name 'ti' is not defined
[2022-06-12 04:18:25,650] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_dag, task_id=choose_best_model, execution_date=20220611T000000, start_date=20220612T041824, end_date=20220612T041825
[2022-06-12 04:18:25,680] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task choose_best_model (name 'ti' is not defined; 3270)
[2022-06-12 04:18:25,711] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-12 04:18:25,834] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
