[2022-06-14 08:51:35,305] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: table_postgres.create_postgres_table manual__2022-06-14T08:34:48.192912+00:00 [queued]>
[2022-06-14 08:51:35,390] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: table_postgres.create_postgres_table manual__2022-06-14T08:34:48.192912+00:00 [queued]>
[2022-06-14 08:51:35,393] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 08:51:35,395] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2022-06-14 08:51:35,397] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 08:51:35,549] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-06-14 08:34:48.192912+00:00
[2022-06-14 08:51:35,585] {standard_task_runner.py:52} INFO - Started process 3804 to run task
[2022-06-14 08:51:35,631] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'table_postgres', 'create_postgres_table', 'manual__2022-06-14T08:34:48.192912+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/create_user.py', '--cfg-path', '/tmp/tmps5fyoi5c', '--error-file', '/tmp/tmptrz2k8yd']
[2022-06-14 08:51:35,636] {standard_task_runner.py:80} INFO - Job 68: Subtask create_postgres_table
[2022-06-14 08:51:36,236] {task_command.py:370} INFO - Running <TaskInstance: table_postgres.create_postgres_table manual__2022-06-14T08:34:48.192912+00:00 [running]> on host 38a912dff3f2
[2022-06-14 08:51:36,810] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=table_postgres
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-06-14T08:34:48.192912+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-14T08:34:48.192912+00:00
[2022-06-14 08:51:36,852] {base.py:68} INFO - Using connection ID 'postgre_sql' for task execution.
[2022-06-14 08:51:36,888] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 186, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.internel" to address: Name or service not known

[2022-06-14 08:51:36,974] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=table_postgres, task_id=create_postgres_table, execution_date=20220614T083448, start_date=20220614T085135, end_date=20220614T085136
[2022-06-14 08:51:37,043] {standard_task_runner.py:97} ERROR - Failed to execute job 68 for task create_postgres_table (could not translate host name "host.docker.internel" to address: Name or service not known
; 3804)
[2022-06-14 08:51:37,127] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-14 08:51:37,484] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
